//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFolio2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFeature
    {
        public int FeatureID { get; set; }
        public string HeaderTitle { get; set; }
        public string HeaderDescription { get; set; }
    }
}
