//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFolio2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblService
    {
        public int ServiceID { get; set; }
        public string ServiceTitle { get; set; }
        public string ServiceImageUrl { get; set; }
        public string Description { get; set; }
    }
}
