//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFolio2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTestimonial
    {
        public int TestimonialID { get; set; }
        public string NameSurname { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
